name: vyatsu_app
description: Мобильный клиент студента Вятского государственного университета

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cubit: ^0.0.8
  flutter_cubit: ^0.0.10
  google_fonts: ^1.1.0
  http: ^0.12.1
  json_annotation: ^3.0.1
  provider: ^4.3.2+2
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  cubit_test: ^0.0.5
  json_serializable: ^3.3.0
  matcher: ^0.12.6
  mockito: ^4.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/images/
  fonts:
      - family:  IconsVyatsu
        fonts:
        - asset: assets/fonts/IconsVyatsu.ttf