/// Flutter icons IconsVyatsu
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsVyatsu
///      fonts:
///       - asset: fonts/IconsVyatsu.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsVyatsu {
  IconsVyatsu._();

  static const _kFontFam = 'IconsVyatsu';
  static const _kFontPkg = null;

  static const IconData logo_vyatsu = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit_to_app = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData session = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfc = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
